# Generated by Django 5.1.2 on 2024-10-24 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("machines", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("sale_date", models.DateField()),
                ("sale_time", models.TimeField()),
                ("quantity", models.IntegerField()),
                ("source_system", models.CharField(max_length=50)),
                ("source_system_id", models.BigIntegerField()),
                ("machine", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="machines.machine")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="products.product")),
            ],
            options={
                "verbose_name": "Sale",
                "verbose_name_plural": "Sales",
                "db_table": "sale",
            },
        ),
    ]
