# Generated by Django 5.1.2 on 2024-10-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Geography",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("postcode", models.CharField(max_length=255, blank=True, null=True)),
            ],
            options={
                "verbose_name": "Geography",
                "verbose_name_plural": "Geographies",
                "db_table": "geography",
            },
        ),
    ]
