# Generated by Django 5.1.2 on 2024-10-24 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("brand_partners", "0001_initial"),
        ("geographies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Machine",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "geography",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="geographies.geography"),
                ),
            ],
            options={
                "verbose_name": "Machine",
                "verbose_name_plural": "Machines",
                "db_table": "machine",
            },
        ),
        migrations.CreateModel(
            name="MachineBrandPartner",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "brand_partner",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="brand_partners.brandpartner"),
                ),
                ("machine", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="machines.machine")),
            ],
            options={
                "verbose_name": "Machine Brand Partner",
                "verbose_name_plural": "Machine Brand Partners",
                "db_table": "machine_brand_partner",
                "unique_together": {("machine", "brand_partner")},
            },
        ),
        migrations.AddField(
            model_name="machine",
            name="brand_partners",
            field=models.ManyToManyField(
                related_name="machines", through="machines.MachineBrandPartner", to="brand_partners.brandpartner"
            ),
        ),
    ]
