"""changed-impression-column-names

Revision ID: a726039113cd
Revises: f7448f4ad562
Create Date: 2024-11-28 15:39:16.743657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a726039113cd'
down_revision = 'f7448f4ad562'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('impression', sa.Column('seconds_exposure', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('impression', sa.Column('advert_playouts', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.alter_column('impression', 'source_system_id',
               existing_type=sa.VARCHAR(),
               comment='\n            ID of the impression in the source system. Combination of the `device_number` and `date`. Must be unique.\n        ',
               existing_comment='\n            ID of the impression in the source system. Combination of the `device_number` and `date`. Must be unique.\n            ',
               existing_nullable=False)
    op.drop_column('impression', 'temperature')
    op.drop_column('impression', 'rainfall')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('impression', sa.Column('rainfall', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('impression', sa.Column('temperature', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('impression', 'source_system_id',
               existing_type=sa.VARCHAR(),
               comment='\n            ID of the impression in the source system. Combination of the `device_number` and `date`. Must be unique.\n            ',
               existing_comment='\n            ID of the impression in the source system. Combination of the `device_number` and `date`. Must be unique.\n        ',
               existing_nullable=False)
    op.drop_column('impression', 'advert_playouts')
    op.drop_column('impression', 'seconds_exposure')
    # ### end Alembic commands ###
