x-common-service: &common-service
  build:
    context: ../
    dockerfile: vendi-docker/Dockerfile
    target: dev
  env_file:
    - ../.env
  environment:
    DATABASE_HOST: vendi-db
    DATABASE_PORT: 5432
    DATABASE_USER: vendi-user
    DATABASE_PASSWORD: vendi-password
    DATABASE_DB: vendi-db
  depends_on:
    vendi-db:
      condition: service_healthy
    vendi-redis:
      condition: service_healthy
  volumes:
    - ../:/backend/vendi

services:
  vendi-service:
    <<: *common-service
    container_name: vendi-service
    ports:
      - "8040:8080"

  vendi-db:
    image: postgres:16-alpine
    container_name: vendi-db
    shm_size: 1G
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: vendi-user
      POSTGRES_PASSWORD: vendi-password
      POSTGRES_DB: vendi-db
    expose:
      - 5432
    ports:
      - "5464:5432"
    env_file:
      - ../.env
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U vendi-user -d vendi-db'" ]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 50

  vendi-redis:
    image: redis:7.4-rc2-alpine
    container_name: vendi-redis
    hostname: vendi-redis
    expose:
      - 6379
    ports:
      - "6364:6379"
    volumes:
      - cache:/data
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 50

  vendi-worker:
    <<: *common-service
    container_name: vendi-worker
    command: vendi_worker

volumes:
  cache:
    driver: local
