# Generated by Django 5.1.2 on 2024-10-24 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("machines", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Impression",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("date", models.DateField()),
                ("total_impressions", models.IntegerField()),
                ("temperature", models.IntegerField()),
                ("rainfall", models.IntegerField()),
                ("source_system", models.CharField(max_length=50)),
                ("source_system_id", models.IntegerField()),
                ("machine", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="machines.machine")),
            ],
            options={
                "verbose_name": "Impression",
                "verbose_name_plural": "Impressions",
                "db_table": "impression",
            },
        ),
    ]
